<<<<<<< HEAD
language: objective-c # lol
osx_image: xcode9.2
=======
language: objective-c
osx_image: xcode9
>>>>>>> Update .travis.yml for Xcode 9 and add seperate build script
xcode_project: DVR.xcodeproj

matrix:
  include:
    - xcode_scheme: DVR-iOS
      xcode_sdk: iphonesimulator
      env:
        - DESTINATION="OS=10.1,name=iPhone 7 Plus"
    - xcode_scheme: DVR-macOS
      xcode_sdk: macosx
      env:
        - DESTINATION="OS X"
    - env:
      - SWIFT_BUILD=true

script: 
  - ./Scripts/travis-build-test.sh

